package pl.com.mnemonic.entities;
// Generated 2016-11-22 19:13:13 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SystemUsers generated by hbm2java
 */
@Entity
@Table(name = "system_users", catalog = "spring_role_manager")
public class SystemUsers implements java.io.Serializable {

	private Integer idSystemUser;
	private String name;
	private String lastName;
	private String email;
	private String password;
	private Set<SystemUserRoles> systemUserRoleses = new HashSet<SystemUserRoles>(0);

	public SystemUsers() {
	}

	public SystemUsers(String email, String password) {
		this.email = email;
		this.password = password;
	}

	public SystemUsers(String name, String lastName, String email, String password,
			Set<SystemUserRoles> systemUserRoleses) {
		this.name = name;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.systemUserRoleses = systemUserRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_system_user", unique = true, nullable = false)
	public Integer getIdSystemUser() {
		return this.idSystemUser;
	}

	public void setIdSystemUser(Integer idSystemUser) {
		this.idSystemUser = idSystemUser;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "last_name", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemUsers")
	public Set<SystemUserRoles> getSystemUserRoleses() {
		return this.systemUserRoleses;
	}

	public void setSystemUserRoleses(Set<SystemUserRoles> systemUserRoleses) {
		this.systemUserRoleses = systemUserRoleses;
	}

}
