package pl.com.mnemonic.ems.entity;
// Generated 2016-01-21 21:51:41 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CategoryAttribute generated by hbm2java
 */
@Entity
@Table(name = "category_attribute", catalog = "estates")
public class CategoryAttribute implements java.io.Serializable {

	private Integer idcategoryAttribute;
	private Category category;
	private Attribute attribute;
	private String role;

	public CategoryAttribute() {
	}

	public CategoryAttribute(Category category, Attribute attribute) {
		this.category = category;
		this.attribute = attribute;
	}

	public CategoryAttribute(Category category, Attribute attribute, String role) {
		this.category = category;
		this.attribute = attribute;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcategory_attribute", unique = true, nullable = false)
	public Integer getIdcategoryAttribute() {
		return this.idcategoryAttribute;
	}

	public void setIdcategoryAttribute(Integer idcategoryAttribute) {
		this.idcategoryAttribute = idcategoryAttribute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_idcategory", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_idattribute", nullable = false)
	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
