package pl.com.mnemonic.ems.entity;
// Generated 2016-01-01 14:22:11 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expense generated by hbm2java
 */
@Entity
@Table(name = "expense", catalog = "estates")
public class Expense implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2381071333775095064L;
	private Integer idexpense;
	private Payment payment;
	private MediaCounter mediaCounter;
	private Facility facility;
	private String type;
	private String name;
	private Date registered;
	private Double amount;
	private String description;
	private String occurence;
	private Integer calculationPeriod;

	public Expense() {
	}

	public Expense(Payment payment, MediaCounter mediaCounter, Facility facility) {
		this.payment = payment;
		this.mediaCounter = mediaCounter;
		this.facility = facility;
	}

	public Expense(Payment payment, MediaCounter mediaCounter, Facility facility, String type, String name,
			Date registered, Double amount, String description, String occurence, Integer calculationPeriod) {
		this.payment = payment;
		this.mediaCounter = mediaCounter;
		this.facility = facility;
		this.type = type;
		this.name = name;
		this.registered = registered;
		this.amount = amount;
		this.description = description;
		this.occurence = occurence;
		this.calculationPeriod = calculationPeriod;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idexpense", unique = true, nullable = false)
	public Integer getIdexpense() {
		return this.idexpense;
	}

	public void setIdexpense(Integer idexpense) {
		this.idexpense = idexpense;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_idpayment", nullable = false)
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "media_counter_idmedia_counter", nullable = false)
	public MediaCounter getMediaCounter() {
		return this.mediaCounter;
	}

	public void setMediaCounter(MediaCounter mediaCounter) {
		this.mediaCounter = mediaCounter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facility_idfacility", nullable = false)
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registered", length = 19)
	public Date getRegistered() {
		return this.registered;
	}

	public void setRegistered(Date registered) {
		this.registered = registered;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "occurence", length = 45)
	public String getOccurence() {
		return this.occurence;
	}

	public void setOccurence(String occurence) {
		this.occurence = occurence;
	}

	@Column(name = "calculationPeriod")
	public Integer getCalculationPeriod() {
		return this.calculationPeriod;
	}

	public void setCalculationPeriod(Integer calculationPeriod) {
		this.calculationPeriod = calculationPeriod;
	}

}
