package pl.com.mnemonic.ems.entity;
// Generated 2015-12-13 18:00:43 by Hibernate Tools 4.0.0.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "estates")
public class Payment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idpayment;
	private Place place;
	private String type;
	private Date duedate;
	private Date dateregistered;
	private String description;
	private Double amount;
	private String account;
	private int placeAddressIdaddress;
	private Set<Expense> expenses = new HashSet<Expense>(0);

	public Payment() {
	}

	public Payment(Place place, Media media, int placeAddressIdaddress) {
		this.place = place;
		this.placeAddressIdaddress = placeAddressIdaddress;
	}

	public Payment(Place place, Media media, String type, Date duedate, Date dateregistered,
			String description, Double amount, String account, int placeAddressIdaddress) {
		this.place = place;
		this.type = type;
		this.duedate = duedate;
		this.dateregistered = dateregistered;
		this.description = description;
		this.amount = amount;
		this.account = account;
		this.placeAddressIdaddress = placeAddressIdaddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpayment", unique = true, nullable = false)
	public Integer getIdpayment() {
		return this.idpayment;
	}

	public void setIdpayment(Integer idpayment) {
		this.idpayment = idpayment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "place_idplace", nullable = false)
	public Place getPlace() {
		return this.place;
	}

	public void setPlace(Place place) {
		this.place = place;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "duedate", length = 10)
	public Date getDuedate() {
		return this.duedate;
	}

	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateregistered", length = 10)
	public Date getDateregistered() {
		return this.dateregistered;
	}

	public void setDateregistered(Date dateregistered) {
		this.dateregistered = dateregistered;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "account", length = 45)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "place_address_idaddress", nullable = false)
	public int getPlaceAddressIdaddress() {
		return this.placeAddressIdaddress;
	}

	public void setPlaceAddressIdaddress(int placeAddressIdaddress) {
		this.placeAddressIdaddress = placeAddressIdaddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payment", orphanRemoval = true)
	public Set<Expense> getExpenses() {
		return expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}
}
