package pl.com.mnemonic.ems.entity;
// Generated 2015-11-15 09:24:20 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;




/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "report", catalog = "estates")
public class Report implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idreport;
	private Placeuser placeuser;
	private MediaCounter mediaCounter;
	private Date date;
	private String type;
	private Double amount;
	private String comment;
	
	public Report() {
	}

	public Report(Placeuser placeuser) {
		this.placeuser = placeuser;
	}

	public Report(Placeuser placeuser, Date date, String type, Double amount, String comment) {
		this.placeuser = placeuser;
		this.date = date;
		this.type = type;
		this.amount = amount;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idreport", unique = true, nullable = false)
	public Integer getIdreport() {
		return this.idreport;
	}

	public void setIdreport(Integer idreport) {
		this.idreport = idreport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "placeuser_idplaceuser", nullable = false)
	public Placeuser getPlaceuser() {
		return this.placeuser;
	}

	public void setPlaceuser(Placeuser placeuser) {
		this.placeuser = placeuser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "comment", length = 100)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "media_counter_idmedia_counter", nullable = false)
	public MediaCounter getMediaCounter() {
		return this.mediaCounter;
	}

	public void setMediaCounter(MediaCounter mediaCounter) {
		this.mediaCounter = mediaCounter;
	}
}
