package pl.com.mnemonic.entity;
// Generated 2016-11-22 19:13:13 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SystemUserRole generated by hbm2java
 */
@Entity
@Table(name = "system_user_roles", catalog = "spring_role_manager")
public class SystemUserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSystemUserRoles;
	private SystemRole systemRole;
	private SystemUser systemUser;

	public SystemUserRole() {
	}

	public SystemUserRole(SystemRole systemRole, SystemUser systemUser) {
		this.systemRole = systemRole;
		this.systemUser = systemUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_system_user_roles", unique = true, nullable = false)
	public Integer getIdSystemUserRoles() {
		return this.idSystemUserRoles;
	}

	public void setIdSystemUserRoles(Integer idSystemUserRoles) {
		this.idSystemUserRoles = idSystemUserRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "system_roles_id_system_roles", nullable = false)
	public SystemRole getSystemRoles() {
		return this.systemRole;
	}

	public void setSystemRoles(SystemRole systemRole) {
		this.systemRole = systemRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "system_users_id_system_user", nullable = false)
	public SystemUser getSystemUsers() {
		return this.systemUser;
	}

	public void setSystemUsers(SystemUser systemUser) {
		this.systemUser = systemUser;
	}

}
